# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/mihir/PRLab/Matrix/Matrix.cache/wt [current_project]
set_property parent.project_path /home/mihir/PRLab/Matrix/Matrix.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths /home/mihir/PRLab/Sources/ip_repo [current_project]
set_property ip_output_repo /home/mihir/PRLab/Matrix/Matrix.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/mihir/PRLab/Matrix/Matrix.srcs/sources_1/bd/matrix_design/hdl/matrix_design_wrapper.v
add_files /home/mihir/PRLab/Matrix/Matrix.srcs/sources_1/bd/matrix_design/matrix_design.bd
set_property used_in_implementation false [get_files -all /home/mihir/PRLab/Matrix/Matrix.srcs/sources_1/bd/matrix_design/ip/matrix_design_processing_system7_0_0/matrix_design_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/mihir/PRLab/Matrix/Matrix.srcs/sources_1/bd/matrix_design/ip/matrix_design_rst_ps7_0_100M_0/matrix_design_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mihir/PRLab/Matrix/Matrix.srcs/sources_1/bd/matrix_design/ip/matrix_design_rst_ps7_0_100M_0/matrix_design_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/mihir/PRLab/Matrix/Matrix.srcs/sources_1/bd/matrix_design/ip/matrix_design_rst_ps7_0_100M_0/matrix_design_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mihir/PRLab/Matrix/Matrix.srcs/sources_1/bd/matrix_design/ip/matrix_design_blk_mem_gen_0_0/matrix_design_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mihir/PRLab/Matrix/Matrix.srcs/sources_1/bd/matrix_design/ip/matrix_design_axi_bram_ctrl_0_0/matrix_design_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mihir/PRLab/Matrix/Matrix.srcs/sources_1/bd/matrix_design/ip/matrix_design_xbar_0/matrix_design_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mihir/PRLab/Matrix/Matrix.srcs/sources_1/bd/matrix_design/ip/matrix_design_axi_timer_0_0/matrix_design_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/mihir/PRLab/Matrix/Matrix.srcs/sources_1/bd/matrix_design/ip/matrix_design_axi_timer_0_0/matrix_design_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mihir/PRLab/Matrix/Matrix.srcs/sources_1/bd/matrix_design/ip/matrix_design_auto_pc_0/matrix_design_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mihir/PRLab/Matrix/Matrix.srcs/sources_1/bd/matrix_design/ip/matrix_design_auto_pc_1/matrix_design_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mihir/PRLab/Matrix/Matrix.srcs/sources_1/bd/matrix_design/ip/matrix_design_auto_pc_2/matrix_design_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mihir/PRLab/Matrix/Matrix.srcs/sources_1/bd/matrix_design/matrix_design_ooc.xdc]
set_property is_locked true [get_files /home/mihir/PRLab/Matrix/Matrix.srcs/sources_1/bd/matrix_design/matrix_design.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top matrix_design_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef matrix_design_wrapper.dcp

catch { report_utilization -file matrix_design_wrapper_utilization_synth.rpt -pb matrix_design_wrapper_utilization_synth.pb }
