# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -ruleid {1}  -id {Timing 38-282}  -string {{CRITICAL WARNING: [Timing 38-282] The design failed to meet the timing requirements. Please see the timing summary report for details on the timing violations.}}  -suppress 
set_msg_config  -ruleid {14}  -id {Common 17-163}  -string {{ERROR: [Common 17-163] Missing value for option 'file', please type 'write_bitstream -help' for usage info.}}  -suppress 
set_msg_config  -ruleid {2}  -id {Labtools 27-2269}  -string {{ERROR: [Labtools 27-2269] No devices detected on target localhost:3121/xilinx_tcf/Digilent/210248782397.
Check cable connectivity and that the target board is powered up then
use the disconnect_hw_server and connect_hw_server to re-register this hardware target.}}  -suppress 
set_msg_config  -ruleid {3}  -id {Labtoolstcl 44-513}  -string {{ERROR: [Labtoolstcl 44-513] HW Target shutdown. Closing target: localhost:3121/xilinx_tcf/Digilent/210248782397}}  -suppress 
set_msg_config  -ruleid {4}  -id {Common 17-170}  -string {{ERROR: [Common 17-170] Unknown option '-effort_level', please type 'place_design -help' for usage info.}}  -suppress 
set_msg_config  -ruleid {5}  -id {Common 17-170}  -string {{ERROR: [Common 17-170] Unknown option '-effor_level', please type 'place_design -help' for usage info.}}  -suppress 
set_msg_config  -ruleid {7}  -id {Common 17-53}  -string {{ERROR: [Common 17-53] User Exception: No open design. Please open an elaborated, synthesized or implemented design before executing this command.}}  -suppress 
set_msg_config  -ruleid {8}  -id {Route 35-39}  -string {{CRITICAL WARNING: [Route 35-39] The design did not meet timing requirements. Please run report_timing_summary for detailed reports.
Resolution: Verify that the timing was met or had small violations at all previous steps (synthesis, placement, power_opt, and phys_opt). Run report_timing_summary and analyze individual timing paths.}}  -suppress 
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/JPEG_Thesis/DARC_DCT_App/DARC_DCT_App.cache/wt [current_project]
set_property parent.project_path C:/JPEG_Thesis/DARC_DCT_App/DARC_DCT_App.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  c:/JPEG_Thesis/RLE/ip_repo/DARC_RLE_1.0
  c:/JPEG_Thesis/RLE
  c:/JPEG_Thesis/ip_repo
  c:/JPEG_Thesis/Quantization
} [current_project]
set_property ip_output_repo c:/JPEG_Thesis/DARC_DCT_App/DARC_DCT_App.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/JPEG_Thesis/DARC_DCT_App/DARC_DCT_App.srcs/sources_1/bd/DARC_DCT_Design/hdl/DARC_DCT_Design_wrapper.vhd
add_files C:/JPEG_Thesis/DARC_DCT_App/DARC_DCT_App.srcs/sources_1/bd/DARC_DCT_Design/DARC_DCT_Design.bd
set_property used_in_implementation false [get_files -all c:/JPEG_Thesis/DARC_DCT_App/DARC_DCT_App.srcs/sources_1/bd/DARC_DCT_Design/ip/DARC_DCT_Design_processing_system7_0_0/DARC_DCT_Design_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/JPEG_Thesis/DARC_DCT_App/DARC_DCT_App.srcs/sources_1/bd/DARC_DCT_Design/ip/DARC_DCT_Design_rst_ps7_0_100M_0/DARC_DCT_Design_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/JPEG_Thesis/DARC_DCT_App/DARC_DCT_App.srcs/sources_1/bd/DARC_DCT_Design/ip/DARC_DCT_Design_rst_ps7_0_100M_0/DARC_DCT_Design_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/JPEG_Thesis/DARC_DCT_App/DARC_DCT_App.srcs/sources_1/bd/DARC_DCT_Design/ip/DARC_DCT_Design_rst_ps7_0_100M_0/DARC_DCT_Design_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JPEG_Thesis/DARC_DCT_App/DARC_DCT_App.srcs/sources_1/bd/DARC_DCT_Design/ip/DARC_DCT_Design_xbar_0/DARC_DCT_Design_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JPEG_Thesis/DARC_DCT_App/DARC_DCT_App.srcs/sources_1/bd/DARC_DCT_Design/ip/DARC_DCT_Design_axi_timer_0_0/DARC_DCT_Design_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/JPEG_Thesis/DARC_DCT_App/DARC_DCT_App.srcs/sources_1/bd/DARC_DCT_Design/ip/DARC_DCT_Design_axi_timer_0_0/DARC_DCT_Design_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JPEG_Thesis/DARC_DCT_App/DARC_DCT_App.srcs/sources_1/bd/DARC_DCT_Design/ip/DARC_DCT_Design_auto_pc_0/DARC_DCT_Design_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/JPEG_Thesis/DARC_DCT_App/DARC_DCT_App.srcs/sources_1/bd/DARC_DCT_Design/DARC_DCT_Design_ooc.xdc]
set_property is_locked true [get_files C:/JPEG_Thesis/DARC_DCT_App/DARC_DCT_App.srcs/sources_1/bd/DARC_DCT_Design/DARC_DCT_Design.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top DARC_DCT_Design_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef DARC_DCT_Design_wrapper.dcp

catch { report_utilization -file DARC_DCT_Design_wrapper_utilization_synth.rpt -pb DARC_DCT_Design_wrapper_utilization_synth.pb }
