// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xmatrix_addition.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XMatrix_addition_CfgInitialize(XMatrix_addition *InstancePtr, XMatrix_addition_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Crtl_bus_BaseAddress = ConfigPtr->Crtl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XMatrix_addition_Start(XMatrix_addition *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMatrix_addition_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_ADDITION_CRTL_BUS_ADDR_AP_CTRL) & 0x80;
    XMatrix_addition_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_ADDITION_CRTL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XMatrix_addition_IsDone(XMatrix_addition *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMatrix_addition_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_ADDITION_CRTL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XMatrix_addition_IsIdle(XMatrix_addition *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMatrix_addition_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_ADDITION_CRTL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XMatrix_addition_IsReady(XMatrix_addition *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMatrix_addition_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_ADDITION_CRTL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XMatrix_addition_EnableAutoRestart(XMatrix_addition *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMatrix_addition_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_ADDITION_CRTL_BUS_ADDR_AP_CTRL, 0x80);
}

void XMatrix_addition_DisableAutoRestart(XMatrix_addition *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMatrix_addition_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_ADDITION_CRTL_BUS_ADDR_AP_CTRL, 0);
}

void XMatrix_addition_InterruptGlobalEnable(XMatrix_addition *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMatrix_addition_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_ADDITION_CRTL_BUS_ADDR_GIE, 1);
}

void XMatrix_addition_InterruptGlobalDisable(XMatrix_addition *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMatrix_addition_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_ADDITION_CRTL_BUS_ADDR_GIE, 0);
}

void XMatrix_addition_InterruptEnable(XMatrix_addition *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMatrix_addition_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_ADDITION_CRTL_BUS_ADDR_IER);
    XMatrix_addition_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_ADDITION_CRTL_BUS_ADDR_IER, Register | Mask);
}

void XMatrix_addition_InterruptDisable(XMatrix_addition *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMatrix_addition_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_ADDITION_CRTL_BUS_ADDR_IER);
    XMatrix_addition_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_ADDITION_CRTL_BUS_ADDR_IER, Register & (~Mask));
}

void XMatrix_addition_InterruptClear(XMatrix_addition *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMatrix_addition_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_ADDITION_CRTL_BUS_ADDR_ISR, Mask);
}

u32 XMatrix_addition_InterruptGetEnabled(XMatrix_addition *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMatrix_addition_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_ADDITION_CRTL_BUS_ADDR_IER);
}

u32 XMatrix_addition_InterruptGetStatus(XMatrix_addition *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMatrix_addition_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_ADDITION_CRTL_BUS_ADDR_ISR);
}

