// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xmatrix_multiply.h"

extern XMatrix_multiply_Config XMatrix_multiply_ConfigTable[];

XMatrix_multiply_Config *XMatrix_multiply_LookupConfig(u16 DeviceId) {
	XMatrix_multiply_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XMATRIX_MULTIPLY_NUM_INSTANCES; Index++) {
		if (XMatrix_multiply_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XMatrix_multiply_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XMatrix_multiply_Initialize(XMatrix_multiply *InstancePtr, u16 DeviceId) {
	XMatrix_multiply_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XMatrix_multiply_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XMatrix_multiply_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

