# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/DARC_DCT_Design/DARC_DCT_Design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DARC_DCT_Design || ORIG_REF_NAME==DARC_DCT_Design}]

# IP: bd/DARC_DCT_Design/ip/DARC_DCT_Design_DARC_DCT_0_0/DARC_DCT_Design_DARC_DCT_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DARC_DCT_Design_DARC_DCT_0_0 || ORIG_REF_NAME==DARC_DCT_Design_DARC_DCT_0_0}]

# IP: bd/DARC_DCT_Design/ip/DARC_DCT_Design_processing_system7_0_0/DARC_DCT_Design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DARC_DCT_Design_processing_system7_0_0 || ORIG_REF_NAME==DARC_DCT_Design_processing_system7_0_0}]

# IP: bd/DARC_DCT_Design/ip/DARC_DCT_Design_ps7_0_axi_periph_0/DARC_DCT_Design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DARC_DCT_Design_ps7_0_axi_periph_0 || ORIG_REF_NAME==DARC_DCT_Design_ps7_0_axi_periph_0}]

# IP: bd/DARC_DCT_Design/ip/DARC_DCT_Design_rst_ps7_0_100M_0/DARC_DCT_Design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DARC_DCT_Design_rst_ps7_0_100M_0 || ORIG_REF_NAME==DARC_DCT_Design_rst_ps7_0_100M_0}]

# IP: bd/DARC_DCT_Design/ip/DARC_DCT_Design_auto_pc_0/DARC_DCT_Design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DARC_DCT_Design_auto_pc_0 || ORIG_REF_NAME==DARC_DCT_Design_auto_pc_0}]

# XDC: bd/DARC_DCT_Design/ip/DARC_DCT_Design_processing_system7_0_0/DARC_DCT_Design_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DARC_DCT_Design_processing_system7_0_0 || ORIG_REF_NAME==DARC_DCT_Design_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/DARC_DCT_Design/ip/DARC_DCT_Design_rst_ps7_0_100M_0/DARC_DCT_Design_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DARC_DCT_Design_rst_ps7_0_100M_0 || ORIG_REF_NAME==DARC_DCT_Design_rst_ps7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/DARC_DCT_Design/ip/DARC_DCT_Design_rst_ps7_0_100M_0/DARC_DCT_Design_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DARC_DCT_Design_rst_ps7_0_100M_0 || ORIG_REF_NAME==DARC_DCT_Design_rst_ps7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/DARC_DCT_Design/ip/DARC_DCT_Design_rst_ps7_0_100M_0/DARC_DCT_Design_rst_ps7_0_100M_0_ooc.xdc

# XDC: bd/DARC_DCT_Design/ip/DARC_DCT_Design_auto_pc_0/DARC_DCT_Design_auto_pc_0_ooc.xdc

# XDC: bd/DARC_DCT_Design/DARC_DCT_Design_ooc.xdc
