# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/jpeg_design/jpeg_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jpeg_design || ORIG_REF_NAME==jpeg_design}]

# IP: bd/jpeg_design/ip/jpeg_design_processing_system7_0_0/jpeg_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jpeg_design_processing_system7_0_0 || ORIG_REF_NAME==jpeg_design_processing_system7_0_0}]

# IP: bd/jpeg_design/ip/jpeg_design_JPEG_PR_0_0/jpeg_design_JPEG_PR_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jpeg_design_JPEG_PR_0_0 || ORIG_REF_NAME==jpeg_design_JPEG_PR_0_0}]

# IP: bd/jpeg_design/ip/jpeg_design_ps7_0_axi_periph_0/jpeg_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jpeg_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==jpeg_design_ps7_0_axi_periph_0}]

# IP: bd/jpeg_design/ip/jpeg_design_rst_ps7_0_100M_0/jpeg_design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jpeg_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==jpeg_design_rst_ps7_0_100M_0}]

# IP: bd/jpeg_design/ip/jpeg_design_DARC_RLE_0_0/jpeg_design_DARC_RLE_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jpeg_design_DARC_RLE_0_0 || ORIG_REF_NAME==jpeg_design_DARC_RLE_0_0}]

# IP: bd/jpeg_design/ip/jpeg_design_xbar_0/jpeg_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jpeg_design_xbar_0 || ORIG_REF_NAME==jpeg_design_xbar_0}]

# IP: bd/jpeg_design/ip/jpeg_design_DARC_HUFFMAN_0_0/jpeg_design_DARC_HUFFMAN_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jpeg_design_DARC_HUFFMAN_0_0 || ORIG_REF_NAME==jpeg_design_DARC_HUFFMAN_0_0}]

# IP: bd/jpeg_design/ip/jpeg_design_axi_timer_0_0/jpeg_design_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jpeg_design_axi_timer_0_0 || ORIG_REF_NAME==jpeg_design_axi_timer_0_0}]

# IP: bd/jpeg_design/ip/jpeg_design_auto_pc_0/jpeg_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jpeg_design_auto_pc_0 || ORIG_REF_NAME==jpeg_design_auto_pc_0}]

# XDC: bd/jpeg_design/ip/jpeg_design_processing_system7_0_0/jpeg_design_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==jpeg_design_processing_system7_0_0 || ORIG_REF_NAME==jpeg_design_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/jpeg_design/ip/jpeg_design_rst_ps7_0_100M_0/jpeg_design_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==jpeg_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==jpeg_design_rst_ps7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/jpeg_design/ip/jpeg_design_rst_ps7_0_100M_0/jpeg_design_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==jpeg_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==jpeg_design_rst_ps7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/jpeg_design/ip/jpeg_design_rst_ps7_0_100M_0/jpeg_design_rst_ps7_0_100M_0_ooc.xdc

# XDC: bd/jpeg_design/ip/jpeg_design_xbar_0/jpeg_design_xbar_0_ooc.xdc

# XDC: bd/jpeg_design/ip/jpeg_design_axi_timer_0_0/jpeg_design_axi_timer_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==jpeg_design_axi_timer_0_0 || ORIG_REF_NAME==jpeg_design_axi_timer_0_0}] {/U0 }]/U0 ]]

# XDC: bd/jpeg_design/ip/jpeg_design_axi_timer_0_0/jpeg_design_axi_timer_0_0_ooc.xdc

# XDC: bd/jpeg_design/ip/jpeg_design_auto_pc_0/jpeg_design_auto_pc_0_ooc.xdc

# XDC: bd/jpeg_design/jpeg_design_ooc.xdc
