# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/huffman_system_sdk/huffman_system_sdk.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==huffman_system_sdk || ORIG_REF_NAME==huffman_system_sdk}]

# IP: bd/huffman_system_sdk/ip/huffman_system_sdk_HUFFMAN_REV2_IP_0_0/huffman_system_sdk_HUFFMAN_REV2_IP_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==huffman_system_sdk_HUFFMAN_REV2_IP_0_0 || ORIG_REF_NAME==huffman_system_sdk_HUFFMAN_REV2_IP_0_0}]

# IP: bd/huffman_system_sdk/ip/huffman_system_sdk_processing_system7_0_0/huffman_system_sdk_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==huffman_system_sdk_processing_system7_0_0 || ORIG_REF_NAME==huffman_system_sdk_processing_system7_0_0}]

# IP: bd/huffman_system_sdk/ip/huffman_system_sdk_ps7_0_axi_periph_0/huffman_system_sdk_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==huffman_system_sdk_ps7_0_axi_periph_0 || ORIG_REF_NAME==huffman_system_sdk_ps7_0_axi_periph_0}]

# IP: bd/huffman_system_sdk/ip/huffman_system_sdk_rst_ps7_0_100M_0/huffman_system_sdk_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==huffman_system_sdk_rst_ps7_0_100M_0 || ORIG_REF_NAME==huffman_system_sdk_rst_ps7_0_100M_0}]

# IP: bd/huffman_system_sdk/ip/huffman_system_sdk_auto_pc_0/huffman_system_sdk_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==huffman_system_sdk_auto_pc_0 || ORIG_REF_NAME==huffman_system_sdk_auto_pc_0}]

# XDC: bd/huffman_system_sdk/ip/huffman_system_sdk_processing_system7_0_0/huffman_system_sdk_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==huffman_system_sdk_processing_system7_0_0 || ORIG_REF_NAME==huffman_system_sdk_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/huffman_system_sdk/ip/huffman_system_sdk_rst_ps7_0_100M_0/huffman_system_sdk_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==huffman_system_sdk_rst_ps7_0_100M_0 || ORIG_REF_NAME==huffman_system_sdk_rst_ps7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/huffman_system_sdk/ip/huffman_system_sdk_rst_ps7_0_100M_0/huffman_system_sdk_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==huffman_system_sdk_rst_ps7_0_100M_0 || ORIG_REF_NAME==huffman_system_sdk_rst_ps7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/huffman_system_sdk/ip/huffman_system_sdk_rst_ps7_0_100M_0/huffman_system_sdk_rst_ps7_0_100M_0_ooc.xdc

# XDC: bd/huffman_system_sdk/ip/huffman_system_sdk_auto_pc_0/huffman_system_sdk_auto_pc_0_ooc.xdc

# XDC: bd/huffman_system_sdk/huffman_system_sdk_ooc.xdc
