# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/bram_design_system/bram_design_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_design_system || ORIG_REF_NAME==bram_design_system}]

# IP: bd/bram_design_system/ip/bram_design_system_processing_system7_0_0/bram_design_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_design_system_processing_system7_0_0 || ORIG_REF_NAME==bram_design_system_processing_system7_0_0}]

# IP: bd/bram_design_system/ip/bram_design_system_ps7_0_axi_periph_0/bram_design_system_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_design_system_ps7_0_axi_periph_0 || ORIG_REF_NAME==bram_design_system_ps7_0_axi_periph_0}]

# IP: bd/bram_design_system/ip/bram_design_system_rst_ps7_0_100M_0/bram_design_system_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_design_system_rst_ps7_0_100M_0 || ORIG_REF_NAME==bram_design_system_rst_ps7_0_100M_0}]

# IP: bd/bram_design_system/ip/bram_design_system_DARC_BRAM2_0_1/bram_design_system_DARC_BRAM2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_design_system_DARC_BRAM2_0_1 || ORIG_REF_NAME==bram_design_system_DARC_BRAM2_0_1}]

# IP: bd/bram_design_system/ip/bram_design_system_DARC_Mux_0_0/bram_design_system_DARC_Mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_design_system_DARC_Mux_0_0 || ORIG_REF_NAME==bram_design_system_DARC_Mux_0_0}]

# IP: bd/bram_design_system/ip/bram_design_system_bram_0_1/bram_design_system_bram_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_design_system_bram_0_1 || ORIG_REF_NAME==bram_design_system_bram_0_1}]

# IP: bd/bram_design_system/ip/bram_design_system_ARM_FPGA_Control_Bus_0_5/bram_design_system_ARM_FPGA_Control_Bus_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_design_system_ARM_FPGA_Control_Bus_0_5 || ORIG_REF_NAME==bram_design_system_ARM_FPGA_Control_Bus_0_5}]

# IP: bd/bram_design_system/ip/bram_design_system_xbar_0/bram_design_system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_design_system_xbar_0 || ORIG_REF_NAME==bram_design_system_xbar_0}]

# IP: bd/bram_design_system/ip/bram_design_system_controller_0_1/bram_design_system_controller_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_design_system_controller_0_1 || ORIG_REF_NAME==bram_design_system_controller_0_1}]

# IP: bd/bram_design_system/ip/bram_design_system_REV2_JPEG_IP_DESIGN_0_0/bram_design_system_REV2_JPEG_IP_DESIGN_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_design_system_REV2_JPEG_IP_DESIGN_0_0 || ORIG_REF_NAME==bram_design_system_REV2_JPEG_IP_DESIGN_0_0}]

# IP: bd/bram_design_system/ip/bram_design_system_axi_timer_0_0/bram_design_system_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_design_system_axi_timer_0_0 || ORIG_REF_NAME==bram_design_system_axi_timer_0_0}]

# IP: bd/bram_design_system/ip/bram_design_system_auto_pc_0/bram_design_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_design_system_auto_pc_0 || ORIG_REF_NAME==bram_design_system_auto_pc_0}]

# XDC: bd/bram_design_system/ip/bram_design_system_processing_system7_0_0/bram_design_system_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bram_design_system_processing_system7_0_0 || ORIG_REF_NAME==bram_design_system_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/bram_design_system/ip/bram_design_system_rst_ps7_0_100M_0/bram_design_system_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bram_design_system_rst_ps7_0_100M_0 || ORIG_REF_NAME==bram_design_system_rst_ps7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/bram_design_system/ip/bram_design_system_rst_ps7_0_100M_0/bram_design_system_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bram_design_system_rst_ps7_0_100M_0 || ORIG_REF_NAME==bram_design_system_rst_ps7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/bram_design_system/ip/bram_design_system_rst_ps7_0_100M_0/bram_design_system_rst_ps7_0_100M_0_ooc.xdc

# XDC: bd/bram_design_system/ip/bram_design_system_xbar_0/bram_design_system_xbar_0_ooc.xdc

# XDC: bd/bram_design_system/ip/bram_design_system_axi_timer_0_0/bram_design_system_axi_timer_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bram_design_system_axi_timer_0_0 || ORIG_REF_NAME==bram_design_system_axi_timer_0_0}] {/U0 }]/U0 ]]

# XDC: bd/bram_design_system/ip/bram_design_system_axi_timer_0_0/bram_design_system_axi_timer_0_0_ooc.xdc

# XDC: bd/bram_design_system/ip/bram_design_system_auto_pc_0/bram_design_system_auto_pc_0_ooc.xdc

# XDC: bd/bram_design_system/bram_design_system_ooc.xdc
