// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xmatrix_multiply.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XMatrix_multiply_CfgInitialize(XMatrix_multiply *InstancePtr, XMatrix_multiply_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Crtl_bus_BaseAddress = ConfigPtr->Crtl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XMatrix_multiply_Start(XMatrix_multiply *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMatrix_multiply_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_MULTIPLY_CRTL_BUS_ADDR_AP_CTRL) & 0x80;
    XMatrix_multiply_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_MULTIPLY_CRTL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XMatrix_multiply_IsDone(XMatrix_multiply *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMatrix_multiply_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_MULTIPLY_CRTL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XMatrix_multiply_IsIdle(XMatrix_multiply *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMatrix_multiply_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_MULTIPLY_CRTL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XMatrix_multiply_IsReady(XMatrix_multiply *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMatrix_multiply_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_MULTIPLY_CRTL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XMatrix_multiply_EnableAutoRestart(XMatrix_multiply *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMatrix_multiply_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_MULTIPLY_CRTL_BUS_ADDR_AP_CTRL, 0x80);
}

void XMatrix_multiply_DisableAutoRestart(XMatrix_multiply *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMatrix_multiply_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_MULTIPLY_CRTL_BUS_ADDR_AP_CTRL, 0);
}

void XMatrix_multiply_InterruptGlobalEnable(XMatrix_multiply *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMatrix_multiply_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_MULTIPLY_CRTL_BUS_ADDR_GIE, 1);
}

void XMatrix_multiply_InterruptGlobalDisable(XMatrix_multiply *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMatrix_multiply_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_MULTIPLY_CRTL_BUS_ADDR_GIE, 0);
}

void XMatrix_multiply_InterruptEnable(XMatrix_multiply *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMatrix_multiply_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_MULTIPLY_CRTL_BUS_ADDR_IER);
    XMatrix_multiply_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_MULTIPLY_CRTL_BUS_ADDR_IER, Register | Mask);
}

void XMatrix_multiply_InterruptDisable(XMatrix_multiply *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMatrix_multiply_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_MULTIPLY_CRTL_BUS_ADDR_IER);
    XMatrix_multiply_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_MULTIPLY_CRTL_BUS_ADDR_IER, Register & (~Mask));
}

void XMatrix_multiply_InterruptClear(XMatrix_multiply *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMatrix_multiply_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_MULTIPLY_CRTL_BUS_ADDR_ISR, Mask);
}

u32 XMatrix_multiply_InterruptGetEnabled(XMatrix_multiply *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMatrix_multiply_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_MULTIPLY_CRTL_BUS_ADDR_IER);
}

u32 XMatrix_multiply_InterruptGetStatus(XMatrix_multiply *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMatrix_multiply_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XMATRIX_MULTIPLY_CRTL_BUS_ADDR_ISR);
}

