// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xmatrix_addition.h"

extern XMatrix_addition_Config XMatrix_addition_ConfigTable[];

XMatrix_addition_Config *XMatrix_addition_LookupConfig(u16 DeviceId) {
	XMatrix_addition_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XMATRIX_ADDITION_NUM_INSTANCES; Index++) {
		if (XMatrix_addition_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XMatrix_addition_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XMatrix_addition_Initialize(XMatrix_addition *InstancePtr, u16 DeviceId) {
	XMatrix_addition_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XMatrix_addition_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XMatrix_addition_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

